services:

  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/mlflow:/home/mlflow/"
    networks:
      - app-network
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "9696:9696"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
